version: '2'
services:
  demoazurespringcloudapi-app:
    image: demoazurespringcloudapi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://demoazurespringcloudapi-mssql:1433;database=DemoAzureSpringCloudApi
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  demoazurespringcloudapi-mssql:
    extends:
      file: mssql.yml
      service: demoazurespringcloudapi-mssql
